services:
  postgres:
    image: postgres:18.2
    container_name: postgres-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: class-db 
      POSTGRES_USER: tjadmin
      POSTGRES_PASSWORD: eshB2RqtU<2Pr]HX

    ports:
      - "5432:5432"

    volumes:
      # - postgres_data:/var/lib/postgresql/data
      - tj-class-postgres-data:/var/lib/postgresql

    networks:
      - tj-class-network

volumes:
  tj-class-postgres-data:
    external: true

networks:
  tj-class-network:
    external: true