services:
  postgres:
    image: postgres:18.2
    container_name: postgres-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: class-db 
      POSTGRES_USER: tjadmin
      POSTGRES_PASSWORD: eshB2RqtU<2Pr]HX

    ports:
      - "5432:5432"

    volumes:
      # - postgres_data:/var/lib/postgresql/data
      - tj-class-postgres-data:/var/lib/postgresql
      # - ./docker/postgres:/docker-entrypoint-initdb.d

    networks:
      - tj-class-network

  go4class-backend:
    container_name: go4class-backend
    build:
      context: .
      dockerfile: Dockerfile
    image: go4class-backend:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAVA_OPTS: >
        -XX:MaxRAMPercentage=75
        -XX:+UseSerialGC
        -XX:+ExitOnOutOfMemoryError
    deploy:
      resources:
        limits:
          memory: 512M
    restart: unless-stopped
    depends_on:
      - postgres

    networks:
      - tj-class-network

volumes:
  tj-class-postgres-data:
    external: true

networks:
  tj-class-network:
    external: true